# Generated by Django 5.2.9 on 2025-12-10 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='Notas del médico')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones / tratamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='scheduling.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Tipo de sangre')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Enfermedades crónicas')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos actuales')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
