# Generated by Django 5.2.9 on 2025-12-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_call_url',
            field=models.URLField(blank=True, help_text='Enlace a la sala de videollamada (Jitsi u otro proveedor).', null=True),
        ),
    ]
