# Generated by Django 5.2.9 on 2025-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_video_call_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='video_call_url',
            field=models.URLField(blank=True, help_text='Enlace a la sala de videollamada.', null=True),
        ),
    ]
